FROM alpine:3.19
RUN apk add --no-cache curl ca-certificates && \
    curl -sL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | tar xz -C /usr/local/bin/ && \
    apk del curl
ENTRYPOINT ["ngrok"]
